name: Build
on:
  push:
  workflow_dispatch:
    inputs:
      creusot_branch:
        description: 'creusot-rs branch'
        required: false
        type: string
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get creusot-rs Git Revision
        run: |
          echo "CREUSOT_REF_NAME=${{ inputs.creusot_branch || 'master' }}" >> $GITHUB_ENV
          echo "CREUSOT_REV=$(curl -s "https://api.github.com/repos/creusot-rs/creusot/branches/${{ inputs.creusot_branch || 'master' }}" | jq -r '.commit.sha')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/jchv/creusot-rs-docker
          tags: |
            type=raw,value=${{ env.CREUSOT_REF_NAME }}
            type=raw,value=${{ env.CREUSOT_REV }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            creusot_ref=${{ env.CREUSOT_REV }}
          provenance: mode=max
          push: true
          sbom: true
        env:
          SOURCE_DATE_EPOCH: 0
